name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.21', '1.20', '1.19', '1.18']
    steps:
      - name: Checkout Code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: ${{ matrix.go }}
      
      - name: Build Go
        run: go build ./...

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@08e2f20817b15149a52b5b3ebe7de50aff2ba8c5

      - name: run test and generate coverage report
        run: go test -race ./... -v -coverprofile=coverage.out

      - name: Upload coverage report 
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808
        with: 
          path: coverage.out
          name: Coverage-report-${{matrix.go}}

      - name: Display coverage report
        run: go tool cover -func=coverage.out
  
